
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = "num id int print println vars mainProg : VarBlc MainBlcVarBlc : vars '{' Dcls '}'Dcls : DclInt DclsDcls : MainBlc : main '{' InstsInsts : AttrInt InstsInsts : Print InstsInsts : Println InstsInsts : '}'Print : print '(' id ')'Println : println '(' id ')'DclInt : int idDclInt : int id numDclInt : int id '=' numAttrInt : id numAttrInt : id '=' num"
    
_lr_action_items = {'vars':([0,],[3,]),'$end':([1,4,11,15,22,23,24,],[0,-1,-5,-9,-6,-7,-8,]),'main':([2,19,],[5,-2,]),'{':([3,5,],[6,7,]),'}':([6,7,8,9,12,13,14,20,21,25,29,31,34,35,36,],[-4,15,19,-4,15,15,15,-3,-12,-15,-13,-16,-14,-10,-11,]),'int':([6,9,21,29,34,],[10,10,-12,-13,-14,]),'id':([7,10,12,13,14,25,27,28,31,35,36,],[16,21,16,16,16,-15,32,33,-16,-10,-11,]),'print':([7,12,13,14,25,31,35,36,],[17,17,17,17,-15,-16,-10,-11,]),'println':([7,12,13,14,25,31,35,36,],[18,18,18,18,-15,-16,-10,-11,]),'num':([16,21,26,30,],[25,29,31,34,]),'=':([16,21,],[26,30,]),'(':([17,18,],[27,28,]),')':([32,33,],[35,36,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'Prog':([0,],[1,]),'VarBlc':([0,],[2,]),'MainBlc':([2,],[4,]),'Dcls':([6,9,],[8,20,]),'DclInt':([6,9,],[9,9,]),'Insts':([7,12,13,14,],[11,22,23,24,]),'AttrInt':([7,12,13,14,],[12,12,12,12,]),'Print':([7,12,13,14,],[13,13,13,13,]),'Println':([7,12,13,14,],[14,14,14,14,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> Prog","S'",1,None,None,None),
  ('Prog -> VarBlc MainBlc','Prog',2,'p_Prog','compiler_yacc.py',29),
  ('VarBlc -> vars { Dcls }','VarBlc',4,'p_VarBlc','compiler_yacc.py',33),
  ('Dcls -> DclInt Dcls','Dcls',2,'p_Dcls','compiler_yacc.py',36),
  ('Dcls -> <empty>','Dcls',0,'p_Dcls_End','compiler_yacc.py',39),
  ('MainBlc -> main { Insts','MainBlc',3,'p_MainBlc','compiler_yacc.py',43),
  ('Insts -> AttrInt Insts','Insts',2,'p_Insts_Attr','compiler_yacc.py',46),
  ('Insts -> Print Insts','Insts',2,'p_Insts_Print','compiler_yacc.py',49),
  ('Insts -> Println Insts','Insts',2,'p_Insts_Println','compiler_yacc.py',52),
  ('Insts -> }','Insts',1,'p_Insts_End','compiler_yacc.py',55),
  ('Print -> print ( id )','Print',4,'p_Print','compiler_yacc.py',59),
  ('Println -> println ( id )','Println',4,'p_Println','compiler_yacc.py',65),
  ('DclInt -> int id','DclInt',2,'p_DclInt','compiler_yacc.py',73),
  ('DclInt -> int id num','DclInt',3,'p_DclInt_Attr','compiler_yacc.py',80),
  ('DclInt -> int id = num','DclInt',4,'p_DclInt_AttrEq','compiler_yacc.py',87),
  ('AttrInt -> id num','AttrInt',2,'p_AttrInt','compiler_yacc.py',94),
  ('AttrInt -> id = num','AttrInt',3,'p_AttrInt_Eq','compiler_yacc.py',100),
]
